### ISSUE TITLE
"America" => "Northern America" or better "USA"

### ISSUE THREAD

**Issue by JazzTp** [JJ/hoborg#6]
Hi, I'm reading the plot:

"After America is defeated by a technologically superior Cuba and Spain, Florida becomes an independent multiracial socialist state which is inmediately at war with the (now diminished) America.

An American Pinkerton agent is sent into that state to recover a mechanical man that has been seen in a circus doing gigs from Pensacola to St. Pitersburg entertaining the masses.

He succeeds, but going back to Washington is not easy. He becomes a railway hobo, accompanied with a hobo cyborg - the hoborg of the title."

During these 13 years in Argentina, I have understood the importance of not calling the USA "America". America is also Canada, Mexico, and all the Central and Southern America states including Argentina extending almost to the South Pole.

No lecturing intended, just constructive contribution: I am Italian and while living in Italy and France I was, as anybody else there, calling "America" the USA.

Cheers!
Nicola

**Comment by JJ** [comment]
Usa is the way to go, I guess. Thanks!

El sábado, 1 de agosto de 2015, Nicola B. Bernardelli <
notifications@github.com> escribió:
> Hi, I'm reading the plot:
>
> "After America is defeated by a technologically superior Cuba and Spain,
Florida becomes an independent multiracial socialist state which is
inmediately at war with the (now diminished) America.
>
> An American Pinkerton agent is sent into that state to recover a
mechanical man that has been seen in a circus doing gigs from Pensacola to
St. Pitersburg entertaining the masses.
>
> He succeeds, but going back to Washington is not easy. He becomes a
railway hobo, accompanied with a hobo cyborg - the hoborg of the title."
>
> During these 13 years in Argentina, I have understood the importance of
not calling the USA "America". America is also Canada, Mexico, and all the
Central and Southern America states including Argentina extending almost to
the South Pole.
>
> No lecturing intended, just constructive contribution: I am Italian and
while living in Italy and France I was, as anybody else there, calling
"America" the USA.
>
> Cheers!
> Nicola
>
> —
> Reply to this email directly or view it on GitHub.<
https://ci4.googleusercontent.com/proxy/41ZO1ljVH1tMpj-Jrlvct9mj0_HXJKDhuU2pHkWhiVgCIkotsghyLMJ5HWBJIH85QJ4SgyCHn2_52G33Aq5qCzYw3rRaaGapRhaW-nBU_14p2lQHkIeHhImM1Yl5AhcPKSwPFKRR-FXyMc3_6jG4xAenMvmpSQ=s0-d-e1-ft#https://github.com/notifications/beacon/AAAB9E4EmqVmEEofkGSpKMqVJJa2qTHPks5ojGFxgaJpZM4Fj56-.gif
>

-- 
JJ

**Comment by JazzTp** [comment]
You're welcome!
